apiVersion: apps/v1
kind: Deployment
metadata: 
  name: web-nginx-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web-nginx
  template:
    metadata:
      name: web-nginx-pod
      labels: 
        app: web-nginx
    spec:
      containers:
      - name: web-nginx
        image: ahmed377/web-nginx
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: "100m"
          limits:
            cpu: "500m"
        volumeMounts:
        - name: website-storage
          mountPath: /usr/share/nginx/html
      volumes:
      - name: website-storage
        persistentVolumeClaim:
          claimName: efs-pvc

        
